# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\vscode_2020\vstestfxh\fxh_qt501\fxh_qt501\qt_000.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 771, 471))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_001 = QtWidgets.QPushButton(self.tab)
        self.btn_001.setGeometry(QtCore.QRect(34, 20, 91, 23))
        self.btn_001.setObjectName("btn_001")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 25, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(140, 55, 81, 16))
        self.label_4.setObjectName("label_4")
        self.btn_002 = QtWidgets.QPushButton(self.tab)
        self.btn_002.setGeometry(QtCore.QRect(34, 50, 91, 23))
        self.btn_002.setObjectName("btn_002")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(140, 85, 81, 16))
        self.label_6.setObjectName("label_6")
        self.btn_003 = QtWidgets.QPushButton(self.tab)
        self.btn_003.setGeometry(QtCore.QRect(34, 80, 91, 23))
        self.btn_003.setObjectName("btn_003")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(140, 25, 81, 16))
        self.label_3.setObjectName("label_3")
        self.btn_A01 = QtWidgets.QPushButton(self.tab_2)
        self.btn_A01.setGeometry(QtCore.QRect(20, 20, 111, 23))
        self.btn_A01.setObjectName("btn_A01")
        self.btn_A02 = QtWidgets.QPushButton(self.tab_2)
        self.btn_A02.setGeometry(QtCore.QRect(20, 50, 111, 23))
        self.btn_A02.setObjectName("btn_A02")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(140, 54, 81, 16))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.btn_B01 = QtWidgets.QPushButton(self.tab_5)
        self.btn_B01.setGeometry(QtCore.QRect(60, 30, 111, 23))
        self.btn_B01.setObjectName("btn_B01")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(190, 35, 81, 16))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btn_C01 = QtWidgets.QPushButton(self.tab_3)
        self.btn_C01.setGeometry(QtCore.QRect(60, 20, 111, 23))
        self.btn_C01.setObjectName("btn_C01")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(185, 23, 81, 16))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(180, 24, 81, 16))
        self.label_5.setObjectName("label_5")
        self.btn_D01 = QtWidgets.QPushButton(self.tab_4)
        self.btn_D01.setGeometry(QtCore.QRect(50, 20, 111, 23))
        self.btn_D01.setObjectName("btn_D01")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "自制工具集"))
        self.btn_001.setToolTip(_translate("MainWindow", "20200521 加入"))
        self.btn_001.setText(_translate("MainWindow", "001-词云"))
        self.label_2.setText(_translate("MainWindow", "20200521 加入"))
        self.label_4.setText(_translate("MainWindow", "20200522 加入"))
        self.btn_002.setToolTip(_translate("MainWindow", "20200521 加入"))
        self.btn_002.setText(_translate("MainWindow", "002-九宫格"))
        self.label_6.setText(_translate("MainWindow", "20200531 加入"))
        self.btn_003.setToolTip(_translate("MainWindow", "20200521 加入"))
        self.btn_003.setText(_translate("MainWindow", "003-词云进阶"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "自制工具(0)"))
        self.label_3.setText(_translate("MainWindow", "20200522 加入"))
        self.btn_A01.setToolTip(_translate("MainWindow", "20200521 加入"))
        self.btn_A01.setText(_translate("MainWindow", "A01-baidu图片下载"))
        self.btn_A02.setToolTip(_translate("MainWindow", "20200521 加入"))
        self.btn_A02.setStatusTip(_translate("MainWindow", "you-get 方式"))
        self.btn_A02.setText(_translate("MainWindow", "A02-视频下载"))
        self.label_7.setText(_translate("MainWindow", "20200602 加入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "爬虫(A)"))
        self.btn_B01.setToolTip(_translate("MainWindow", "20200521 加入"))
        self.btn_B01.setText(_translate("MainWindow", "B01-热力地图"))
        self.label_9.setText(_translate("MainWindow", "20200608 加入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "统计显示"))
        self.btn_C01.setToolTip(_translate("MainWindow", "20200604 加入"))
        self.btn_C01.setText(_translate("MainWindow", "C01-图片水印"))
        self.label_8.setText(_translate("MainWindow", "20200604 加入"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "图形(C)"))
        self.label_5.setText(_translate("MainWindow", "20200522 加入"))
        self.btn_D01.setToolTip(_translate("MainWindow", "20200521 加入"))
        self.btn_D01.setText(_translate("MainWindow", "D01-TableGrid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "数据库相关(D)"))
