# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\vscode_2020\vstestfxh\fxh_qt501\fxh_qt501\qt_003.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qt003(object):
    def setupUi(self, qt003):
        qt003.setObjectName("qt003")
        qt003.resize(720, 561)
        self.label = QtWidgets.QLabel(qt003)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label.setObjectName("label")
        self.t_file = QtWidgets.QLineEdit(qt003)
        self.t_file.setGeometry(QtCore.QRect(100, 30, 481, 20))
        self.t_file.setObjectName("t_file")
        self.btn_select_file = QtWidgets.QPushButton(qt003)
        self.btn_select_file.setGeometry(QtCore.QRect(580, 30, 31, 23))
        self.btn_select_file.setObjectName("btn_select_file")
        self.groupBox = QtWidgets.QGroupBox(qt003)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 681, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 71, 41))
        self.label_3.setObjectName("label_3")
        self.btn_select_file_probit = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_file_probit.setGeometry(QtCore.QRect(570, 70, 31, 23))
        self.btn_select_file_probit.setObjectName("btn_select_file_probit")
        self.t_file_probit = QtWidgets.QLineEdit(self.groupBox)
        self.t_file_probit.setGeometry(QtCore.QRect(90, 70, 481, 20))
        self.t_file_probit.setObjectName("t_file_probit")
        self.t_file_2 = QtWidgets.QLineEdit(qt003)
        self.t_file_2.setGeometry(QtCore.QRect(110, 140, 401, 20))
        self.t_file_2.setObjectName("t_file_2")
        self.label_2 = QtWidgets.QLabel(qt003)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_2.setObjectName("label_2")
        self.btn_select_file_2 = QtWidgets.QPushButton(qt003)
        self.btn_select_file_2.setGeometry(QtCore.QRect(510, 140, 31, 23))
        self.btn_select_file_2.setObjectName("btn_select_file_2")
        self.btn_show_pic = QtWidgets.QPushButton(qt003)
        self.btn_show_pic.setGeometry(QtCore.QRect(540, 140, 75, 23))
        self.btn_show_pic.setObjectName("btn_show_pic")
        self.groupBox_2 = QtWidgets.QGroupBox(qt003)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 200, 501, 331))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lbl_pic = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_pic.setGeometry(QtCore.QRect(40, 110, 411, 211))
        self.lbl_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pic.setMidLineWidth(1)
        self.lbl_pic.setText("")
        self.lbl_pic.setObjectName("lbl_pic")
        self.t_aim_file = QtWidgets.QLineEdit(self.groupBox_2)
        self.t_aim_file.setGeometry(QtCore.QRect(90, 80, 381, 20))
        self.t_aim_file.setObjectName("t_aim_file")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 451, 41))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 271, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_all = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rb_all.setChecked(True)
        self.rb_all.setObjectName("rb_all")
        self.horizontalLayout.addWidget(self.rb_all)
        self.rb_top = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rb_top.setObjectName("rb_top")
        self.horizontalLayout.addWidget(self.rb_top)
        self.btn_cloud = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_cloud.setGeometry(QtCore.QRect(320, 20, 75, 23))
        self.btn_cloud.setObjectName("btn_cloud")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 61, 41))
        self.label_4.setObjectName("label_4")
        self.groupBox_3 = QtWidgets.QGroupBox(qt003)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 120, 681, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lbl_pic_orig = QtWidgets.QLabel(qt003)
        self.lbl_pic_orig.setGeometry(QtCore.QRect(540, 180, 161, 101))
        self.lbl_pic_orig.setText("")
        self.lbl_pic_orig.setObjectName("lbl_pic_orig")
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.t_file.raise_()
        self.btn_select_file.raise_()
        self.t_file_2.raise_()
        self.label_2.raise_()
        self.btn_select_file_2.raise_()
        self.btn_show_pic.raise_()
        self.lbl_pic_orig.raise_()

        self.retranslateUi(qt003)
        QtCore.QMetaObject.connectSlotsByName(qt003)

    def retranslateUi(self, qt003):
        _translate = QtCore.QCoreApplication.translate
        qt003.setWindowTitle(_translate("qt003", "词云02"))
        self.label.setText(_translate("qt003", "文件路径"))
        self.btn_select_file.setText(_translate("qt003", "..."))
        self.groupBox.setTitle(_translate("qt003", "内容选择"))
        self.label_3.setText(_translate("qt003", "<html><head/><body><p><span style=\" font-size:8pt;\">屏蔽内容</span></p><p><span style=\" font-size:8pt;\">的文件路径</span></p></body></html>"))
        self.btn_select_file_probit.setText(_translate("qt003", "..."))
        self.label_2.setText(_translate("qt003", "背景文件路径："))
        self.btn_select_file_2.setText(_translate("qt003", "..."))
        self.btn_show_pic.setText(_translate("qt003", "图片预览"))
        self.groupBox_2.setTitle(_translate("qt003", "结果"))
        self.groupBox_4.setTitle(_translate("qt003", "词云范围"))
        self.rb_all.setText(_translate("qt003", "全篇文字"))
        self.rb_top.setText(_translate("qt003", "Top 50 高频词"))
        self.btn_cloud.setText(_translate("qt003", "生成词云"))
        self.label_4.setText(_translate("qt003", "<html><head/><body><p>生成的词云</p><p>图片位置</p></body></html>"))
        self.groupBox_3.setTitle(_translate("qt003", "GroupBox"))
