# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\vscode_2020\vstestfxh\fxh_qt501\fxh_qt501\qt_C01.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qtC01(object):
    def setupUi(self, qtC01):
        qtC01.setObjectName("qtC01")
        qtC01.resize(720, 526)
        self.label = QtWidgets.QLabel(qtC01)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label.setObjectName("label")
        self.t_file = QtWidgets.QLineEdit(qtC01)
        self.t_file.setGeometry(QtCore.QRect(80, 30, 291, 20))
        self.t_file.setObjectName("t_file")
        self.btn_Watermark = QtWidgets.QPushButton(qtC01)
        self.btn_Watermark.setGeometry(QtCore.QRect(20, 160, 75, 23))
        self.btn_Watermark.setObjectName("btn_Watermark")
        self.t_aim_file = QtWidgets.QLineEdit(qtC01)
        self.t_aim_file.setGeometry(QtCore.QRect(20, 190, 381, 20))
        self.t_aim_file.setObjectName("t_aim_file")
        self.groupBox = QtWidgets.QGroupBox(qtC01)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 421, 131))
        self.groupBox.setObjectName("groupBox")
        self.t_text = QtWidgets.QLineEdit(self.groupBox)
        self.t_text.setGeometry(QtCore.QRect(70, 50, 181, 20))
        self.t_text.setObjectName("t_text")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_2.setObjectName("label_2")
        self.btn_select_file = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_file.setGeometry(QtCore.QRect(360, 20, 31, 23))
        self.btn_select_file.setObjectName("btn_select_file")
        self.groupBox_2 = QtWidgets.QGroupBox(qtC01)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 421, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lbl_pic = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_pic.setGeometry(QtCore.QRect(30, 30, 321, 211))
        self.lbl_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pic.setMidLineWidth(1)
        self.lbl_pic.setText("")
        self.lbl_pic.setObjectName("lbl_pic")
        self.groupBox_3 = QtWidgets.QGroupBox(qtC01)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 160, 241, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.rb_1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_1.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.rb_1.setObjectName("rb_1")
        self.rb_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_2.setGeometry(QtCore.QRect(170, 20, 61, 16))
        self.rb_2.setChecked(False)
        self.rb_2.setObjectName("rb_2")
        self.rb_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_3.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.rb_3.setObjectName("rb_3")
        self.rb_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.rb_4.setGeometry(QtCore.QRect(170, 90, 61, 16))
        self.rb_4.setChecked(True)
        self.rb_4.setObjectName("rb_4")
        self.groupBox_4 = QtWidgets.QGroupBox(qtC01)
        self.groupBox_4.setGeometry(QtCore.QRect(450, 10, 251, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lbl_pic_orig = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_pic_orig.setGeometry(QtCore.QRect(20, 30, 221, 101))
        self.lbl_pic_orig.setText("")
        self.lbl_pic_orig.setObjectName("lbl_pic_orig")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.t_file.raise_()
        self.btn_Watermark.raise_()
        self.t_aim_file.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()

        self.retranslateUi(qtC01)
        QtCore.QMetaObject.connectSlotsByName(qtC01)

    def retranslateUi(self, qtC01):
        _translate = QtCore.QCoreApplication.translate
        qtC01.setWindowTitle(_translate("qtC01", "图片加文字水印01"))
        self.label.setText(_translate("qtC01", "文件路径"))
        self.btn_Watermark.setText(_translate("qtC01", "加入水印"))
        self.groupBox.setTitle(_translate("qtC01", "图片选择"))
        self.t_text.setText(_translate("qtC01", "范例文字"))
        self.label_2.setText(_translate("qtC01", "水印文字："))
        self.btn_select_file.setText(_translate("qtC01", "..."))
        self.groupBox_2.setTitle(_translate("qtC01", "结果"))
        self.groupBox_3.setTitle(_translate("qtC01", "水印位置"))
        self.rb_1.setText(_translate("qtC01", "左上角"))
        self.rb_2.setText(_translate("qtC01", "右上角"))
        self.rb_3.setText(_translate("qtC01", "左下角"))
        self.rb_4.setText(_translate("qtC01", "右下角"))
        self.groupBox_4.setTitle(_translate("qtC01", "预览"))
