# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\vscode_2020\vstestfxh\fxh_qt501\fxh_qt501\qt_001.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qt001(object):
    def setupUi(self, qt001):
        qt001.setObjectName("qt001")
        qt001.resize(720, 595)
        self.label = QtWidgets.QLabel(qt001)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label.setObjectName("label")
        self.t_file = QtWidgets.QLineEdit(qt001)
        self.t_file.setGeometry(QtCore.QRect(80, 30, 481, 20))
        self.t_file.setObjectName("t_file")
        self.btn_select_file = QtWidgets.QPushButton(qt001)
        self.btn_select_file.setGeometry(QtCore.QRect(560, 30, 31, 23))
        self.btn_select_file.setObjectName("btn_select_file")
        self.btn_read = QtWidgets.QPushButton(qt001)
        self.btn_read.setGeometry(QtCore.QRect(590, 30, 75, 23))
        self.btn_read.setObjectName("btn_read")
        self.btn_cloud = QtWidgets.QPushButton(qt001)
        self.btn_cloud.setGeometry(QtCore.QRect(30, 340, 75, 23))
        self.btn_cloud.setObjectName("btn_cloud")
        self.te_text = QtWidgets.QTextEdit(qt001)
        self.te_text.setGeometry(QtCore.QRect(30, 60, 631, 181))
        self.te_text.setObjectName("te_text")
        self.lbl_pic = QtWidgets.QLabel(qt001)
        self.lbl_pic.setGeometry(QtCore.QRect(60, 370, 411, 211))
        self.lbl_pic.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_pic.setMidLineWidth(1)
        self.lbl_pic.setObjectName("lbl_pic")
        self.t_aim_file = QtWidgets.QLineEdit(qt001)
        self.t_aim_file.setGeometry(QtCore.QRect(110, 340, 381, 20))
        self.t_aim_file.setObjectName("t_aim_file")
        self.groupBox = QtWidgets.QGroupBox(qt001)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 681, 241))
        self.groupBox.setObjectName("groupBox")
        self.t_file_2 = QtWidgets.QLineEdit(qt001)
        self.t_file_2.setGeometry(QtCore.QRect(110, 270, 401, 20))
        self.t_file_2.setObjectName("t_file_2")
        self.label_2 = QtWidgets.QLabel(qt001)
        self.label_2.setGeometry(QtCore.QRect(20, 270, 101, 16))
        self.label_2.setObjectName("label_2")
        self.btn_select_file_2 = QtWidgets.QPushButton(qt001)
        self.btn_select_file_2.setGeometry(QtCore.QRect(510, 270, 31, 23))
        self.btn_select_file_2.setObjectName("btn_select_file_2")
        self.btn_show_pic = QtWidgets.QPushButton(qt001)
        self.btn_show_pic.setGeometry(QtCore.QRect(540, 270, 75, 23))
        self.btn_show_pic.setObjectName("btn_show_pic")
        self.groupBox_2 = QtWidgets.QGroupBox(qt001)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 501, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(qt001)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 250, 681, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lbl_pic_orig = QtWidgets.QLabel(qt001)
        self.lbl_pic_orig.setGeometry(QtCore.QRect(540, 310, 161, 101))
        self.lbl_pic_orig.setObjectName("lbl_pic_orig")
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.label.raise_()
        self.t_file.raise_()
        self.btn_select_file.raise_()
        self.btn_read.raise_()
        self.btn_cloud.raise_()
        self.te_text.raise_()
        self.lbl_pic.raise_()
        self.t_aim_file.raise_()
        self.t_file_2.raise_()
        self.label_2.raise_()
        self.btn_select_file_2.raise_()
        self.btn_show_pic.raise_()
        self.lbl_pic_orig.raise_()

        self.retranslateUi(qt001)
        QtCore.QMetaObject.connectSlotsByName(qt001)

    def retranslateUi(self, qt001):
        _translate = QtCore.QCoreApplication.translate
        qt001.setWindowTitle(_translate("qt001", "词云01"))
        self.label.setText(_translate("qt001", "文件路径"))
        self.btn_select_file.setText(_translate("qt001", "..."))
        self.btn_read.setText(_translate("qt001", "Read"))
        self.btn_cloud.setText(_translate("qt001", "生成词云"))
        self.lbl_pic.setText(_translate("qt001", "TextLabel"))
        self.groupBox.setTitle(_translate("qt001", "内容选择"))
        self.label_2.setText(_translate("qt001", "背景文件路径："))
        self.btn_select_file_2.setText(_translate("qt001", "..."))
        self.btn_show_pic.setText(_translate("qt001", "图片预览"))
        self.groupBox_2.setTitle(_translate("qt001", "结果"))
        self.groupBox_3.setTitle(_translate("qt001", "GroupBox"))
        self.lbl_pic_orig.setText(_translate("qt001", "TextLabel"))
