# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\vscode_2020\vstestfxh\fxh_qt501\fxh_qt501\Tl_Split_Pic01.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Split_Pic(object):
    def setupUi(self, Form_Split_Pic):
        Form_Split_Pic.setObjectName("Form_Split_Pic")
        Form_Split_Pic.resize(943, 718)
        self.groupBox = QtWidgets.QGroupBox(Form_Split_Pic)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 821, 91))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 54, 12))
        self.label.setObjectName("label")
        self.t_pic_path = QtWidgets.QLineEdit(self.groupBox)
        self.t_pic_path.setGeometry(QtCore.QRect(80, 40, 461, 31))
        self.t_pic_path.setObjectName("t_pic_path")
        self.btn_select_pic = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_pic.setGeometry(QtCore.QRect(542, 40, 31, 31))
        self.btn_select_pic.setObjectName("btn_select_pic")
        self.btn_split9 = QtWidgets.QPushButton(self.groupBox)
        self.btn_split9.setGeometry(QtCore.QRect(573, 40, 75, 31))
        self.btn_split9.setObjectName("btn_split9")
        self.btn_select_pic_2 = QtWidgets.QPushButton(self.groupBox)
        self.btn_select_pic_2.setGeometry(QtCore.QRect(630, 90, 31, 31))
        self.btn_select_pic_2.setObjectName("btn_select_pic_2")
        self.l_pic_orig = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_orig.setGeometry(QtCore.QRect(19, 146, 201, 161))
        self.l_pic_orig.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_orig.setObjectName("l_pic_orig")
        self.l_pic_01 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_01.setGeometry(QtCore.QRect(238, 148, 201, 161))
        self.l_pic_01.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_01.setLineWidth(1)
        self.l_pic_01.setObjectName("l_pic_01")
        self.l_pic_02 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_02.setGeometry(QtCore.QRect(442, 148, 201, 161))
        self.l_pic_02.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_02.setObjectName("l_pic_02")
        self.l_pic_03 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_03.setGeometry(QtCore.QRect(646, 148, 201, 161))
        self.l_pic_03.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_03.setObjectName("l_pic_03")
        self.l_pic_04 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_04.setGeometry(QtCore.QRect(238, 312, 201, 161))
        self.l_pic_04.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_04.setObjectName("l_pic_04")
        self.l_pic_06 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_06.setGeometry(QtCore.QRect(647, 313, 201, 161))
        self.l_pic_06.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_06.setObjectName("l_pic_06")
        self.l_pic_05 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_05.setGeometry(QtCore.QRect(443, 312, 201, 161))
        self.l_pic_05.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_05.setObjectName("l_pic_05")
        self.l_pic_08 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_08.setGeometry(QtCore.QRect(443, 476, 201, 161))
        self.l_pic_08.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_08.setObjectName("l_pic_08")
        self.l_pic_09 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_09.setGeometry(QtCore.QRect(647, 477, 201, 161))
        self.l_pic_09.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_09.setObjectName("l_pic_09")
        self.l_pic_07 = QtWidgets.QLabel(Form_Split_Pic)
        self.l_pic_07.setGeometry(QtCore.QRect(238, 476, 201, 161))
        self.l_pic_07.setFrameShape(QtWidgets.QFrame.Box)
        self.l_pic_07.setObjectName("l_pic_07")
        self.l_new_dir = QtWidgets.QLineEdit(Form_Split_Pic)
        self.l_new_dir.setGeometry(QtCore.QRect(318, 120, 421, 20))
        self.l_new_dir.setObjectName("l_new_dir")
        self.btn_open = QtWidgets.QPushButton(Form_Split_Pic)
        self.btn_open.setGeometry(QtCore.QRect(740, 120, 41, 23))
        self.btn_open.setObjectName("btn_open")
        self.label_2 = QtWidgets.QLabel(Form_Split_Pic)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_Split_Pic)
        self.label_3.setGeometry(QtCore.QRect(240, 123, 71, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form_Split_Pic)
        QtCore.QMetaObject.connectSlotsByName(Form_Split_Pic)

    def retranslateUi(self, Form_Split_Pic):
        _translate = QtCore.QCoreApplication.translate
        Form_Split_Pic.setWindowTitle(_translate("Form_Split_Pic", "切割九宫格"))
        self.groupBox.setTitle(_translate("Form_Split_Pic", "Function:"))
        self.label.setText(_translate("Form_Split_Pic", "图片路径:"))
        self.btn_select_pic.setText(_translate("Form_Split_Pic", "..."))
        self.btn_split9.setText(_translate("Form_Split_Pic", "Split"))
        self.btn_select_pic_2.setText(_translate("Form_Split_Pic", "..."))
        self.l_pic_orig.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_01.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_02.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_03.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_04.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_06.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_05.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_08.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_09.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.l_pic_07.setText(_translate("Form_Split_Pic", "TextLabel"))
        self.btn_open.setText(_translate("Form_Split_Pic", "Open"))
        self.label_2.setText(_translate("Form_Split_Pic", "源文件:"))
        self.label_3.setText(_translate("Form_Split_Pic", "新文件路径:"))
